### ISSUE TITLE
Create Epics under Software Requirement and Software Testing

### ISSUE THREAD

**Issue by deep08032000** [urstrulykkr/smarter-university-system#14]
Create Epics under MVP Software Requirement and Software Testing
task 3: create user stories
task 4: prioritize user stories
task 5: create API test inputs 
task 6: unit test
This is an Activity for EPIC #4

**Comment by urstrulykkr** [comment]
Created 4 epics for the mention tasks in the issue description (project description) #6 #7 #8 #9
