### ISSUE TITLE
Create Activities under Epic: "Prioritize User Stories"

### ISSUE THREAD

**Issue by rgoel22** [urstrulykkr/smarter-university-system#19]
This is an Activity for EPIC #4

**Comment by deep08032000** [comment]
Created Activities: - #25 #26 #27 #28 #29 #30 #31 #32 #34 #35 #36 #37 #38 #39.

**Comment by urstrulykkr** [comment]
Created activities #54  #55 #57

**Comment by rgoel22** [comment]
created activity #56 #58
