### ISSUE TITLE
Understanding the User Stories

### ISSUE THREAD

**Issue by deep08032000** [urstrulykkr/smarter-university-system#25]
Understanding the User Stories so that we can give priority. This is an activity for epic #7

**Comment by rgoel22** [comment]
discussed user stories in the group and understood the relevance of each story

**Comment by PujanAvaiya** [comment]
Discussed and understood the user stories.

**Comment by urstrulykkr** [comment]
Discussed user stories and got clear understanding.

**Comment by deep08032000** [comment]
Discussed the user stories and understood them.

**Comment by akashperni** [comment]
discussed the user stories and understood them
